Sources/Knit/Module/ModuleAssembler.swift
Sources/Knit/Module/ScopedModuleAssembler.swift

The ability to use other assemblies isn't something that ever got used so I'm taking it out. I don't think this is a particular issue for performance but less code means less places for performance issues to hide.

Remove the ability to use the regular Assembly type in Knit

---

Package.swift
Sources/Knit/Container+MainActor.swift
Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift
Sources/KnitCodeGen/Registration.swift
Sources/KnitCodeGen/TypeSafetySourceFile.swift
Tests/KnitCodeGenTests/RegistrationParsingTests.swift
Tests/KnitCodeGenTests/TypeSafetySourceFileTests.swift

This allows `container.register(ServiceA.self) { @MainActor in ServiceA() }` to be generated as
```
extension Resolver {
@MainActor func serviceA() -> ServiceA
}
```
Any other assembly registrations will then need to be marked as @MainActor in order to consume the resolver function. The structure can be extended to support other concurrency patterns like async in the future.

Add support for registering factories on the main thread

---

Knit.podspec

Adds the swift version to match the package file. This is to see if it will fix pipelines which are erroring on the podspec.

Bump to version 1.0.3 and set the swift version

---

Package.swift

At cash we always consume the library via the podspec. This fixes build issues when consuming via SPM

Set minimum iOS version in the package file

---

Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift
Tests/KnitCodeGenTests/RegistrationParsingTests.swift

This fixes some `@MainActor` parsing issues when used with parameters or when explicitly using the `mainActorFactory` param.
I was originally going to support `container.register(A.self) { @MainActor (r: Resolver, a: Arg) in ...` but having main actor there will not compile so the code must explicitly list the mainActorFactory param.

Fix unhandled cases when parsing main actor registrations

---

Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift
Sources/KnitCodeGen/KnitDirectives.swift
Sources/KnitCodeGen/Registration.swift
Sources/KnitCodeGen/TypeSafetySourceFile.swift
Tests/KnitCodeGenTests/KnitDirectivesTests.swift
Tests/KnitCodeGenTests/RegistrationParsingTests.swift
Tests/KnitCodeGenTests/TypeSafetySourceFileTests.swift

This is to handle the case where a type is public with an `@_spi` modifier. The generated resolver needs to also be marked with the same `@_spi` modifier. I used knit directives to supply this information as the parser doesn't know about the original type.
This is a fairly rare case that happened to come up ideally we should support it.
Example error when trying to use `@_spi(Testing) protocol MySPIType` inside DI:
```
Generated/KnitDITypeSafety: error: cannot use protocol 'MySPIType' here; it is SPI
public func mySPIType(file: StaticString = #fileID, function: StaticString = #function, line: UInt = #line) -> MySPIType {
```

Add knit directive to handle types marked with @_spi

---

Sources/Knit/Container+MainActor.swift

The original main actor work only adding registrations for the common cases. This adds options for all remaining cases matching what is available for regular registrations.
This code is copied directly from https://github.com/Swinject/Swinject/pull/570. Once that PR merges this can be removed.

Add missing registration options for main actor

---

CLI/Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift
CLI/Sources/KnitCodeGen/Registration.swift
CLI/Tests/KnitCodeGenTests/RegistrationParsingTests.swift

We should retain all type attributes on the arguments except for the `@escaping` attribute.

Retain type attributes for Registration Arguments

---

CLI/Package.resolved
CLI/Package.swift
CLI/README.md
Example/KnitExample.xcodeproj/project.pbxproj
Example/KnitExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Plugins/KnitBuildPlugin/KnitBuildPlugin.swift

This allows consumers who specify the package with a git repo URL to be able to consume the build plugin from that top level package.

Move SPM plugin product to top-level package

---

CLI/Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift
CLI/Sources/KnitCodeGen/TypeSafetySourceFile.swift
CLI/Sources/KnitCodeGen/UnitTestSourceFile.swift
CLI/Tests/KnitCodeGenTests/RegistrationParsingTests.swift
CLI/Tests/KnitCodeGenTests/TypeSafetySourceFileTests.swift
CLI/Tests/KnitCodeGenTests/UnitTestSourceFileTests.swift

Previously we were dropping `@escaping` when parsing the argument type declaration, but then adding it back upon writing the type safety source file. However this meant that an attributed typealias such as `@escaping ClosureActionTypeAlias` would drop the attribute on parsing, but we would have no way to know to add it back upon writing the type safety methods.
Now we do not make any modifications to the attributes on type declarations for arguments. When generating properties for those types, `@escaping` is always dropped as it is implicit (and including it explicitly is a compilation error).
This also uncovered an issue with argument identifier uniqueness for closures. We should use the identifier when determining uniqueness, not the type, as all closure types map to the same …

Fix treatment of `@escaping` attribute on registration arguments and fix identifier uniqueness bug

---

Docs/Modules.md
Sources/Knit/Module/ModuleAssembler.swift
Sources/Knit/Module/ModuleAssembly.swift
Sources/Knit/Module/ScopedModuleAssembler.swift
Tests/KnitTests/ModuleAssemblerTests.swift
Tests/KnitTests/ModuleAssemblyOverrideTests.swift
Tests/KnitTests/ModuleCycleTests.swift
Tests/KnitTests/ScopedModuleAssemblerTests.swift
Tests/KnitTests/SynchronizationTests.swift

`ModuleAssembly` no longer is subclassed from the Swinject `Assembly` type to allow the protocol definition to enforce that all registrations happen on the main actor.
This caused assemblers to have to be instantiated on the main thread, I'm not expecting any issues from this.

Enforce module assembly happens on the main actor

---

Sources/KnitCodeGen/AssemblyParser.swift
Sources/KnitCommand/GenCommand.swift
Tests/KnitCodeGenTests/AssemblyParsingTests.swift

We now always use Knit with TargetResolver parsing so remove the flag and use the behavior that always respects TargetResolvers.

Remove “use target resolver” flag

---

Sources/KnitCodeGen/AssemblyParser.swift
Sources/KnitCodeGen/AssemblyParsing.swift
Sources/KnitCommand/GenCommand.swift
Tests/KnitCodeGenTests/AssemblyParsingTests.swift

Declaring a TargetResolver is now required for all assemblies.

Remove defaultExtensionTargetResolver option

---

Sources/KnitCodeGen/AssemblyParsing.swift
Sources/KnitCodeGen/Configuration.swift
Tests/KnitCodeGenTests/AssemblyParsingTests.swift

The base type for assemblies is now `ModuleAssembly`.

Remove support for `Swinject.Assembly` as the base assembly type

---

Sources/Knit/Module/Container+AbstractRegistration.swift
Tests/KnitTests/ModuleAssemblerTests.swift

Registered placeholders should match the service type and name of the AbstractRegistration, otherwise there are incorrect placeholders created.

Fix AbstractRegistration placeholder bug

---

Sources/Knit/Module/Container+AbstractRegistration.swift
Tests/KnitTests/AbstractRegistrationTests.swift

Normally when we an abstract registration is created a placeholder during testing that will cause a fatal error making it easier to understand what has gone wrong. But for optional services it's possible to simply return nil and allow tests to continue along normally without the service.

Create OptionalAbstractRegistration type

---

Sources/KnitCodeGen/TypeNamer.swift
Tests/KnitCodeGenTests/TypeNamerTests.swift

This better objc style naming where there are multiple capital letters as a prefix `NSURLSession` isn't quite correct, but it's better than `nSURLSession`.

Improve type name generation of prefixed names

---

Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift
Tests/KnitCodeGenTests/RegistrationParsingTests.swift

This fixes the build failure in the example app.

Automatically make autoregister closures @escaping

---

Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift

Previously it was placing the error on the parent `register` call rather than on the `.implements` call which was actually at issue.

Fix line attachment for syntax error

---

Sources/Knit/Module/Container+AbstractRegistration.swift
Tests/KnitTests/AbstractRegistrationTests.swift

The RegistrationKey needs to match the original service type otherwise validation of abstract registrations will fail. Also the `serviceType` property is used in error messaging to identify the actual service type for the registration (not the unwrapped service type).

Fix the RegistrationKey for OptionalAbstractRegistrations

---

Sources/Knit/Module/DependencyBuilder.swift
Sources/Knit/Module/ModuleAssembly.swift
Sources/KnitCodeGen/TypeSafetySourceFile.swift
Tests/KnitCodeGenTests/ConfigurationSetTests.swift
Tests/KnitCodeGenTests/TypeSafetySourceFileTests.swift

This removes the need for some casts like `if ref.type is any AbstractAssembly.Type` which it turns out have a heavy [performance penalty in large apps](https://www.emergetools.com/blog/posts/SwiftProtocolConformance). 
This makes the code a little bit more complex but for a large app saves ~100ms in startup time.

Improve performance of DependencyBuilder

---

Sources/KnitCodeGen/UnitTestSourceFile.swift
Tests/KnitCodeGenTests/UnitTestSourceFileTests.swift

The service name is used as part of naming the properties on the generated unit test struct, so it also needs to be sanitized.

Sanitize the Service name used for Argument unit tests

---

Sources/KnitCodeGen/TypeNamer.swift
Tests/KnitCodeGenTests/TypeNamerTests.swift

Adds handling for publishers, subjects, providers and factories that commonly need a custom getter-named annotation.

Add handling for common cases inside TypeNamer

---

Sources/KnitCodeGen/KnitDirectives.swift
Sources/KnitCodeGen/TypeSafetySourceFile.swift
Tests/KnitCodeGenTests/ConfigurationSetTests.swift
Tests/KnitCodeGenTests/KnitDirectivesTests.swift

The `_autoInstantiate` and `_assemblyFlags` functions are generated in order to improve assembler performance for large projects. In some assemblies these functions may be generated incorrectly due to an extension conforming to `AutoInitModuleAssembly`. 
`// @knit disable-performance-gen` can be used to disable this code gen so it can be done manually or use the default implementation fallback.

Add Knit directive to disable code gen of performance functions

---

Sources/Swinject/Container.Arguments.erb
Sources/Swinject/Container.Arguments.swift
Sources/Swinject/Container.swift
Sources/Swinject/_Resolver.swift
Tests/SwinjectTests/ContainerTests.DebugHelper.swift
Tests/SwinjectTests/ContainerTests.swift

There is a potential bug with resolution when using parent-child containers and shadowed registrations. This fix ensures that when performing resolution that a parent container can never have access to registrations in a child container. Previously, the container that received the `resolve()` call was captured and used for later factory invocations, and if that receiver was a child that also had a shadowed registration of the parent then the bug could emerge.
This implements the same change as https://github.com/Swinject/Swinject/pull/567 but does not retain an option to use the old behavior. Instead, we are considering the old Swinject behavior to be a bug, and are directly fixing for Knit.

Fix Resolver hierarchy + shadowed registration resolution

---

Sources/Knit/Module/ModuleAssembler.swift
Sources/Swinject/Container.TypeForwarding.swift
Sources/Swinject/Container.swift
Tests/SwinjectTests/ContainerTests.Speed.swift
Tests/SwinjectTests/SynchronizedTests.swift

All containers will now be synchronized with a lock. This also gets rid of the behavior of having a secondary “view” container that is synchronized while the container that holds all the registrations is unsynchronized.

Only allow for synchronized containers when using Knit

---

Docs/CommentCommands.md
README.md

It seemed like there were enough knit comment options for it to live in a separate doc.

Break CommentCommands into a separate documentation file and update

---

Sources/KnitCodeGen/AssemblyParsing.swift
Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift
Sources/KnitCodeGen/SyntaxError.swift
Tests/KnitCodeGenTests/AssemblyParsingTests.swift

They should be attached to the trivia line above the syntax node.

Fix error messages for comment commands

---

Docs/CommentCommands.md
Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift
Sources/KnitCodeGen/KnitDirectives.swift
Sources/KnitCodeGen/Registration.swift
Sources/KnitCodeGen/TypeSafetySourceFile.swift
Tests/KnitCodeGenTests/AssemblyParsingTests.swift
Tests/KnitCodeGenTests/ConfigurationSetTests.swift
Tests/KnitCodeGenTests/KnitDirectivesTests.swift
Tests/KnitCodeGenTests/RegistrationParsingTests.swift
Tests/KnitCodeGenTests/TypeSafetySourceFileTests.swift

Nowhere is currently using the `getter-callAsFunction` directive and removing it simplifies the code and the documentation. I've left it called getter-named but it may change to getter-alias in the future.

Remove getter-callAsFunction directive

---

Docs/CommentCommands.md
Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift
Sources/KnitCodeGen/KnitDirectives.swift
Sources/KnitCodeGen/Registration.swift
Tests/KnitCodeGenTests/KnitDirectivesTests.swift
Tests/KnitCodeGenTests/RegistrationEncodingTests.swift
Tests/KnitCodeGenTests/RegistrationParsingTests.swift

This adds a `// @knit custom("...")` directive which knit simply passes through into the JSON output. This allows external apps to define custom tags that can be consumed by scripts.
The current planned usage is to have something like `// @knit custom("skip_validation")` which will be consumed by an external validate command to provide an escape hatch for edge cases.
I'm not particularly wedded to the name `custom` so if anyone has a suggestion please let me know.

Add custom directive to be consumed by external scripts

---

Sources/KnitMacrosImplementations/ResolvableMacro.swift
Tests/KnitMacrosTests/ResolvableTests.swift

2 changes to the Resolvable macro
* If a function or init is marked as `@MainActor` then the generated function also will be
* When applied to a static function the resulting function will have the same name rather than `make`. This is to allow using `@Resolvable` on functions in an enum factory.

Add MainActor support for the Resolvable macro

---

Docs/CommentCommands.md
Example/KnitExample/KnitExampleAssembly.swift
Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift
Sources/KnitCodeGen/KnitDirectives.swift
Tests/KnitCodeGenTests/AssemblyParsingTests.swift
Tests/KnitCodeGenTests/KnitDirectivesTests.swift
Tests/KnitCodeGenTests/RegistrationParsingTests.swift

Better describes the behavior of this feature.

Rename `getter-named` command to `alias`

---

Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift
Tests/KnitCodeGenTests/AssemblyParsingTests.swift

I didn't think about this during the initial implementation, but when I went to add tags this didn't work how I expected.

Apply custom tags at the assembly level to all registrations

---

Docs/Macros.md
Sources/KnitMacros/MacroPropertyWrappers.swift
Sources/KnitMacrosImplementations/ResolvableMacro.swift
Tests/KnitMacrosTests/ResolvableTests.swift
Tests/KnitMacrosTests/SwinjectResolutionTests.swift

I added this because I couldn't think of a way this would work in all cases. Take these 2 parameters as an example
```
logger: Logger? = nil,
notificationCenter: NotificationCenter = .default
```
In the case of the `logger` I probably want the DI graph to resolve the logger and the default is to make testing easier. 
In the case of `notificationCenter` I probably want to use the default in the real app and change it for testing.
`@UseDefault` removes this ambiguity. I originally thought about doing the inverse and explicitly disabling defaults but that means the developer error will show up at runtime while this way should cause a compile time error

Add @UseDefault property wrapper for Resolvable macro

---

Sources/KnitMacrosImplementations/ResolvableMacro.swift
Tests/KnitMacrosTests/ResolvableTests.swift

`type.name.text` was only pulling out the base type and not the generic parameters which caused a mismatch when generating the name for the resolver call.

Add support for generic types to the Resolvable macro

---

Example/KnitExample.xcodeproj/project.pbxproj
Package.swift
Sources/KnitCodeGen/ConfigurationSet.swift
Sources/KnitCodeGen/UnitTestSourceFile.swift
Sources/KnitTesting/Resolver+Asserts.swift
Tests/KnitCodeGenTests/ConfigurationSetTests.swift
Tests/KnitCodeGenTests/UnitTestSourceFileTests.swift

Rather than generating these functions in the modules that use them they move into the KnitTesting module and are imported.
I've updated the example app to use this as well as putting up a POC in cash-ios https://github.com/squareup/cash-ios/pull/60190

Create KnitTesting module to prevent generating assertResolve functions

---

Docs/Macros.md
Sources/KnitMacrosImplementations/ResolvableMacro.swift
Tests/KnitMacrosTests/ResolvableTests.swift

`@Resolvable` was failing on optional parameters. This adds support so they work as expected. `https://github.com/cashapp/knit/pull/254` clarifies how defaults work with optional values.

Add support for optional parameters to the Resolvable macro

---

Sources/KnitCodeGen/TypeNamer.swift
Tests/KnitCodeGenTests/TypeNamerTests.swift

Fixes some incorrect naming that became an issue due to always generating the non aliased resolver function.

Add TypeNamer handling for multiple generics

---

Sources/KnitCodeGen/Configuration.swift
Tests/KnitCodeGenTests/RegistrationEncodingTests.swift

I wanted to use this value as part of validation but it was missing.

Add targetResolver into the coding keys for Configuration

---

Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift
Sources/KnitCodeGen/Registration.swift
Sources/KnitCodeGen/TypeSafetySourceFile.swift
Tests/KnitCodeGenTests/AssemblyParsingTests.swift
Tests/KnitCodeGenTests/RegistrationParsingTests.swift

SwinjectAutoregistration was already removed in https://github.com/cashapp/knit/pull/259. This removes the parsing support from Knit.

Remove Autoregister support from Knit

---

Sources/Knit/Module/ModuleAssembly.swift

Temporary revert so this change can be part of the next release
This reverts commit 23468ec5bd33a58311a2bd2e8cf8461fa626a4ac.

Revert "Remove @MainActor annotation from assemble"

---

Sources/Knit/Container.swift

We can now name the TargetResolver in the error message when the container has been released.

Add TargetResolver to weak unwrap fatalError message

---

Sources/Knit/Future+Async.swift
Sources/KnitCodeGen/TypeNamer.swift
Tests/KnitCodeGenTests/TypeNamerTests.swift
Tests/KnitTests/MainActorTests.swift

Provide code use examples of async initializers and test coverage.

MainActor tests

---

Sources/KnitCodeGen/HeaderSourceFile.swift
Sources/KnitCodeGen/NamedRegistrationGroup.swift
Sources/KnitCodeGen/SourceGen/NamedRegistrationGroup+SourceCode.swift
Sources/KnitCodeGen/SwiftSyntax+Helpers.swift
Sources/KnitCodeGen/TypeSafetySourceFile.swift
Tests/KnitCodeGenTests/NamedRegistrationGroupSourceTests.swift
Tests/KnitCodeGenTests/NamedRegistrationGroupTests.swift
Tests/KnitCodeGenTests/TypeSafetySourceFileTests.swift

* If a group of named registrations all have the same `#if` condition then the resolver and the enum are both wrapped in the same condition.
* If registrations in the group have different `#if` conditions, the resolver will not have a condition and the enum cases will be wrapped in `#if` conditions from the individual registrations.

Add support for macro conditions to named enums

---

Sources/Knit/Container.swift
Sources/Knit/Module/ModuleAssembler.swift
Sources/Knit/Module/ScopedModuleAssembler.swift
Tests/KnitTests/AbstractRegistrationTests.swift
Tests/KnitTests/ModuleAssemblerTests.swift
Tests/KnitTests/ServiceCollectorTests.swift

This change is to prevent the following errors coming up during testing. The containers get automatically created but since it checks the resolver first an error is raised in the logs which increases noise when looking for real issues.
```
Swinject: Resolution failed. Expected registration:
{ Service: Container<AccountResolver>, Factory: Resolver -> Container<AccountResolver> }
```

Create ContainerManager to prevent needing to directly check for Container registrations

---

Sources/Knit/Module/DependencyBuilder.swift
Tests/KnitTests/ComplexDependencyTests.swift

This solves a niche issue where an assembler has multiple inputs and is using default fake implementations.
This issue occurs with the following conditions
* AssemblyA depends on the abstract AssemblyB
* RealAssemblyB is the implementation for AssemblyB
* FakeAssemblyB exists in the graph and the assembler is setup to allow fakes
* AssemblyA and RealAssemblyB are provided as input modules to the assembly and AssemblyA is first
In this case the expectation is that since RealAssemblyB is provided as an input module the fake shouldn't be automatically used since an explicit implementation is provided. But since AssemblyA pulls AssemblyB in as a dependency before RealAssemblyB is processed the graph ends up with both the fake and the real implementation.

Prevent fakes from being pulled in when a real implementation was provided

---

Sources/Knit/Module/DependencyBuilder.swift

This solves an edge cases where an assembly may end up being instantiated more than once due to how the graph is built. 
I can't figure out a small case to replicate this, but this safety prevents crashes when adding validation for overridden registrations.

Prevent duplicate assemblies being created

---

Sources/Knit/Container+MainActorRegistration.swift
Sources/Knit/Container+Registration.swift
Sources/Knit/Container.swift
Sources/Knit/Module/Container+AbstractRegistration.swift
Sources/Knit/Resolver+Additions.swift
Sources/Knit/Resolver.swift
Sources/Knit/ServiceCollection/Container+ServiceCollection.swift
Sources/Knit/ServiceCollection/Resolver+ServiceCollection.swift
Sources/KnitCodeGen/TypeSafetySourceFile.swift
Sources/KnitTesting/Resolver+Asserts.swift
Tests/KnitCodeGenTests/ConfigurationSetTests.swift
Tests/KnitCodeGenTests/TypeSafetySourceFileTests.swift
Tests/KnitTests/AbstractRegistrationTests.swift
Tests/KnitTests/MainActorTests.swift
Tests/KnitTests/ModuleAssemblerTests.swift
Tests/KnitTests/ServiceCollectorTests.swift
Tests/KnitTests/SynchronizationTests.swift

Add file, function, and line information from call site to released container fatalError. This will allow individual retain cycles to be distinguished from each other in crash reporting.

Reporting improvements for released container error

---

Sources/KnitMacrosImplementations/ResolvableMacro.swift
Tests/KnitMacrosTests/ResolvableTests.swift

Allows for nested types that contain a `.`

Add MemberTypeSyntax support for Resolvable macro

---

Sources/KnitCodeGen/ConfigurationSet.swift
Sources/knit-cli/GenCommand.swift
Tests/KnitCodeGenTests/ConfigurationSetTests.swift

This adds optional enforcement that all abstract registrations are declared in abstract assemblies.

Add strict abstract option to gen command

---

Sources/KnitCodeGen/AssemblyParser.swift
Sources/KnitCodeGen/AssemblyParsing.swift
Sources/KnitCodeGen/ConfigurationSet.swift
Sources/KnitCodeGen/FunctionCallRegistrationParsing.swift
Sources/knit-cli/GenCommand.swift
Tests/KnitCodeGenTests/AssemblyParsingTests.swift
Tests/KnitCodeGenTests/ConfigurationSetTests.swift

The way I implemented this the first time helped to cleanup cash-ios but it didn't do a good job of surfacing the errors in a friendly way. This version raises errors in the same pathway for the `nonAbstract` error.
I realised that there are significant performance benefits possible by enforcing splitting out abstract assemblies so I got rid of it as a configurable parameter to allow deleting the replacement code in a future PR.

Force strict abstract assemblies

---

Sources/Knit/Module/DependencyBuilder.swift
Sources/Knit/Module/ModuleAssembler.swift
Tests/KnitTests/ModuleAssemblerTests.swift
Tests/KnitTests/ModuleAssemblyOverrideTests.swift
Tests/KnitTests/ScopedModuleAssemblerTests.swift

`DependencyBuilder` collects assemblies for ModuleAssembler to assemble. But once that is complete there isn't a need to hold onto them any longer. Assemblies are usually lightweight so this doesn't save much memory, but does keep the memory graph cleaner.

Release assemblies after the assembler finishes

---

.github/workflows/swift.yml
Package.swift

I've seen odd CI build failures that happen on 5.10. Easier to drop the unused version rather than trying to dig through the issues.

Update Package.swift to 6.0

---

Package.swift
Sources/KnitCodeGen/AssemblyParsing.swift
Tests/KnitCodeGenTests/AssemblyParsingTests.swift

If the resolver type included a period then it would not be parsed and the build would fail.

Fix parsing issue for TargetResolver including a module
